### ISSUE TITLE
error in mytonctrl status cmd 

### ISSUE THREAD

**Issue by conan-xyz** [ton-blockchain/mytonctrl#133]
[debug]   14.07.2023, 13:47:27.248 (UTC)  <Logging>     Start WritingLogFile thread.
[debug]   14.07.2023, 13:47:27.248 (UTC)  <SelfTesting> Start SelfTesting thread.
[debug]   14.07.2023, 13:47:27.248 (UTC)  <LocdbSaving> Start LocaldbSaving thread.
[info]    14.07.2023, 13:47:27.248 (UTC)  <MainThread>  Start program '/usr/src/mytonctrl/mytonctrl.py'
Welcome to the console. Enter 'help' to display the help menu.
MyTonCtrl> status
[warning] <MainThread>  GetValidatorEfficiency warning: efficiency not found.
[warning]  <MainThread> GetValidatorStatus warning: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

Error: Command '['/usr/bin/ton/lite-client/lite-client', '--global-config', '/usr/bin/ton/global.config.json', '--verbosity', '0', '--cmd', 'runmethodfull -1:3333333333333333333333333333333333333333333333333333333333333333 list_complaints 1689276168', '-i', '5']' timed out after 3 seconds

**Comment by igroman787** [comment]
Everything looks so that your local node is not yet synchronized and the program takes information from public servers. They may sometimes not respond and this is normal.
This error will disappear after synchronization of your local node.
You can also run your command multiple times and hope you don't end up on an overloaded server.
