### ISSUE TITLE
mytonctrl help

### ISSUE THREAD

**Issue by gercamjr** [ton-blockchain/mytonctrl#32]
I was able to successfully install mytonctrl on Ubuntu 20.04 to try to figure out how to mine from the pow givers. I am able to start mytonctrl and check the status. I followed the instructions in the mytonctrl/docs/en/manual_ubuntu.txt (step 5. bonus) and set the powAddr and set the minerAddr, but I could not see the command to start the miner inside mytonctrl. I guess I don't understand how setting these two configurations (powAddr and minerAddr) will start the mining process, or how can I see if I am mining successfully?

Is mytonctrl what I need to use to start mining?

**Comment by igroman787** [comment]
Mytonctrl - is one of the options for mining coins from PoW givers.
After setting the parameters powAddr and minerAddr, mytcontrl will automatically start mining. To check, you can run htop and see the load of your processors - almost all of them will be loaded at 100%.

**Comment by PhilipPavo** [comment]
@igroman787 hi, I am also set up powAddr and minerAddr. I see CPU usage 100% but nothing happens, I didn't receive any coins.  I tried both types of givers.

**Comment by igroman787** [comment]
The mining process is very complex and requires a lot of computing power.
To theoretically calculate the approximate reward for a day, we need to find out your hash rate (the `hr` command inside mytonctrl).
For example my hashrate:
`[speed: 9.92212e + 07 hps]`

In addition to the hash rate, we need a value for how many nanokoins we can get in one hash (public calculated data):
tonmine.xyz -> find `nanocoins per hash`
It is equal to `0.003` nanocoins, or` 0.000000000003` coins

Now we can calculate how much we can theoretically get the moment per day:
`99221200 * 0.000000000003 * 86400` = `25,71813504` coins.
But since the minimum PoW-giver reward is 100 coins, we will have to work 4 days to receive our first reward)

And all these calculations are theoretical, since the mining process is a job related to probability

**Comment by Naikras** [comment]
Hey! I use Google translate.
Perhaps I’ll ask a stupid question, but is there any way to run mytonctrl on a machine with 1 gigabyte of RAM and one core? I just rented an Amazon server for free, I want to start mining for an experiment

**Comment by awesome-doge** [comment]
I think pow related code should be removed in the future.
Keep project code lean.
