### ISSUE TITLE
удаленный кошелек - не работает status

### ISSUE THREAD

**Issue by gutkati** [ton-blockchain/mytonctrl#81]
После удаления дефолтного кошелька через dw (dw validator_wallet_001), теперь не работает status. Выходит такая ошибка: 
Error: GetWalletFromFile error: Private key not found: /usr/local/bin/mytoncore/wallets/validator_wallet_001
Что нужно сделать и  как корректно удалять кошельки?
Подскажите, при создании ноды создается деф кошелек, но его адрес не совпадает с адресом локального валидатора, почему?  
И вопрос есть ли где то полный faq по работе ноды, сети, список всех команд и подкоманд mytonctrl (set, get).  И возможно ли еще запустить ноду в тестнете?

**Comment by igroman787** [comment]
This is normal behavior. When deleting the validator wallet, Mytonctrl will give an error, as it will not be able to work without it.
If you have created another wallet and want to use it as a validator wallet, then use the command: `set validatorWalletName <new-wallet-name>`

The validator address from command `status` may differ slightly (first and last few characters) from command `wl`, since in the second case the address will be displayed with `non-bouncable` flag while the wallet is inactive.

Most likely there is no complete documentation. All that is currently on Mytonctrl: `mytonctrl/docs/en/`. Although as they say the best documentation is the source code :)

To install Mytonctrl on a testnet, use command: `sudo bash install.sh -m full -c https://ton.org/testnet-global.config.json`
